package model;
// Generated 17/04/2016 11:47:35 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detalleventa generated by hbm2java
 */
@Entity
@Table(name="detalleventa"
    ,catalog="supermercado"
)
public class Detalleventa  implements java.io.Serializable {


     private Integer idDetalleVenta;
     private Producto producto;
     private Venta venta;
     private Integer cantidad;
     private Double total;

    public Detalleventa() {
    }

    public Detalleventa(Producto producto, Venta venta, Integer cantidad, Double total) {
       this.producto = producto;
       this.venta = venta;
       this.cantidad = cantidad;
       this.total = total;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_detalleVenta", unique=true, nullable=false)
    public Integer getIdDetalleVenta() {
        return this.idDetalleVenta;
    }
    
    public void setIdDetalleVenta(Integer idDetalleVenta) {
        this.idDetalleVenta = idDetalleVenta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="producto")
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="venta")
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }

    
    @Column(name="cantidad")
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="total", precision=22, scale=0)
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }




}


